/**
 * Type definitions for the ToB Sales Private Record Tool
 * All data types are designed for local-first, encrypted storage
 */

// ============ Customer Status ============
export type CustomerStatus = 'potential' | 'following' | 'intention' | 'closed' | 'lost';

// ============ Competitor Status ============
export type CompetitorStatus = 'involved' | 'competing' | 'won' | 'lost';

// ============ Contact Role ============
export type ContactRole = 'decision_maker' | 'influencer' | 'user' | 'gatekeeper';

// ============ Follow-up Type ============
export type FollowUpType = 'phone' | 'meeting' | 'email' | 'wechat' | 'visit' | 'other';

// ============ Problem Severity ============
export type ProblemSeverity = 'low' | 'medium' | 'high' | 'critical';

// ============ Problem Status ============
export type ProblemStatus = 'unsolved' | 'solving' | 'solved';

// ============ Reminder Type ============
export type ReminderType = 'follow_up' | 'task' | 'report';

// ============ Resource Type ============
export type ResourceType = 'channel' | 'partner' | 'expert' | 'tool';

// ============ Report Type ============
export type ReportType = 'weekly' | 'monthly' | 'customer';

// ============ Export Format ============
export type ExportFormat = 'json' | 'csv' | 'excel' | 'pdf' | 'markdown';

// ============ Competitor Analysis ============
export interface CompetitorAnalysis {
  id: string;
  customerId: string;
  name: string;
  status: CompetitorStatus;
  theirStrengths: string;
  theirWeaknesses: string;
  ourAdvantages: string;
  notes: string;
  createdAt: number;
  updatedAt: number;
}

// ============ Customer ============
export interface Customer {
  id: string;
  companyName: string;
  industry: string;
  scale: string;
  address: string;
  website: string;
  source: string;
  budget: string;
  decisionCycle: string;
  status: CustomerStatus;
  needs: string;
  painPoints: string;
  decisionFactors: string;
  riskLevel: string;
  winProbability: number; // 0-100
  tags: string[];
  notes: string;
  createdAt: number;
  updatedAt: number;
}

// ============ Contact ============
export interface Contact {
  id: string;
  customerId: string;
  name: string;
  title: string;
  department: string;
  phone: string;   // encrypted
  email: string;   // encrypted
  wechat: string;  // encrypted
  role: ContactRole;
  influenceScore: number; // 1-5
  personality: string;
  communicationPreference: string;
  personalInfo: string; // encrypted
  isKeyDecisionMaker: boolean;
  notes: string;
  createdAt: number;
  updatedAt: number;
}

// ============ Follow-up Record ============
export interface FollowUp {
  id: string;
  customerId: string;
  contactId: string;
  type: FollowUpType;
  customType: string;
  content: string;
  keyPoints: string;
  result: string;
  objections: string;
  mentionedCompetitors: string;
  nextFollowUpTime: number | null;
  attachments: string[]; // local encrypted file references
  createdAt: number;
  updatedAt: number;
}

// ============ Problem & Experience ============
export interface Problem {
  id: string;
  title: string;
  description: string;
  severity: ProblemSeverity;
  status: ProblemStatus;
  attemptedSolutions: AttemptedSolution[];
  finalSolution: string;
  lessonsLearned: string;
  tags: string[];
  relatedCustomerId: string;
  relatedFollowUpId: string;
  createdAt: number;
  updatedAt: number;
}

export interface AttemptedSolution {
  description: string;
  result: string;
  timestamp: number;
}

// ============ Resource ============
export interface Resource {
  id: string;
  type: ResourceType;
  name: string;
  contactInfo: string; // encrypted
  expertise: string;
  networkDescription: string;
  relationshipType: string;
  relationshipStrength: number; // 1-5
  tags: string[];
  notes: string;
  relatedCustomerIds: string[];
  relatedProblemIds: string[];
  createdAt: number;
  updatedAt: number;
}

// ============ Reminder ============
export interface Reminder {
  id: string;
  type: ReminderType;
  title: string;
  description: string;
  dueTime: number;
  customerId: string;
  followUpId: string;
  advanceMinutes: number; // how many minutes before to remind
  isRepeating: boolean;
  repeatIntervalMinutes: number;
  isCompleted: boolean;
  completedAt: number | null;
  createdAt: number;
  updatedAt: number;
}

// ============ Report ============
export interface Report {
  id: string;
  type: ReportType;
  title: string;
  content: string;
  startDate: number;
  endDate: number;
  customerId: string;
  autoGenerated: boolean;
  createdAt: number;
}

// ============ App Settings ============
export interface AppSettings {
  theme: 'light' | 'dark';
  language: 'zh' | 'en';
  autoReportEnabled: boolean;
  autoReportDay: number; // 0=Sunday for weekly, day of month for monthly
  autoReportType: 'weekly' | 'monthly';
  biometricAuthEnabled: boolean;
  cloudBackupEnabled: boolean;
  lastBackupTime: number | null;
}

// ============ Encrypted Record Wrapper ============
export interface EncryptedRecord {
  id: string;
  storeName: string;
  encryptedData: ArrayBuffer;
  iv: Uint8Array;
  tag: string; // for integrity verification
  createdAt: number;
  updatedAt: number;
}

// ============ Security Status ============
export interface SecurityStatus {
  isEncrypted: boolean;
  algorithm: string;
  keyDerivation: string;
  iterations: number;
  storageUsed: number;
  lastVerified: number;
}

// ============ Dashboard Stats ============
export interface DashboardStats {
  todayFollowUps: FollowUp[];
  weekNewCustomers: number;
  weekFollowUpCount: number;
  weekClosedCount: number;
  weekProblemsSolved: number;
  statusDistribution: Record<CustomerStatus, number>;
  recentUpdates: Array<{
    type: 'customer' | 'followup' | 'problem';
    id: string;
    title: string;
    updatedAt: number;
  }>;
  pendingProblems: Problem[];
  pendingReminders: Reminder[];
}

// ============ Navigation ============
export type PageId =
  | 'dashboard'
  | 'customers'
  | 'customer-detail'
  | 'contacts'
  | 'followups'
  | 'problems'
  | 'resources'
  | 'reminders'
  | 'reports'
  | 'export'
  | 'settings'
  | 'trust'
  | 'login';
