import { useState } from 'react';
import { useApp } from '../lib/store';
import { Report, ReportType } from '../lib/types';
import { customerStatusLabels, followUpTypeLabels, formatDateTime, formatDate, downloadFile } from '../lib/utils';
import { FileText, Trash2, Download } from 'lucide-react';

export default function Reports() {
  const { reports, customers, followUps, problems, contacts, addReport, deleteReport, showNotification } = useApp();
  const [generating, setGenerating] = useState(false);
  const [reportType, setReportType] = useState<ReportType>('weekly');
  const [selectedCustomerId, setSelectedCustomerId] = useState('');

  const generateReport = async () => {
    setGenerating(true);
    try {
      const now = Date.now();
      let startDate: number;
      let title: string;

      if (reportType === 'weekly') {
        const d = new Date();
        d.setDate(d.getDate() - 7);
        startDate = d.getTime();
        title = `周报 - ${formatDate(startDate)} 至 ${formatDate(now)}`;
      } else if (reportType === 'monthly') {
        const d = new Date();
        d.setMonth(d.getMonth() - 1);
        startDate = d.getTime();
        title = `月报 - ${formatDate(startDate)} 至 ${formatDate(now)}`;
      } else {
        startDate = new Date(new Date().getFullYear(), 0, 1).getTime();
        const customer = customers.find((c) => c.id === selectedCustomerId);
        title = `客户报告 - ${customer?.companyName || '未知'}`;
      }

      const periodFollowUps = followUps.filter((f) => f.createdAt >= startDate && f.createdAt <= now);
      const periodCustomers = customers.filter((c) => c.createdAt >= startDate && c.createdAt <= now);
      const periodProblems = problems.filter((p) => p.updatedAt >= startDate && p.updatedAt <= now);

      const statusCounts: Record<string, number> = {};
      customers.forEach((c) => {
        statusCounts[c.status] = (statusCounts[c.status] || 0) + 1;
      });

      const typeCounts: Record<string, number> = {};
      periodFollowUps.forEach((f) => {
        typeCounts[f.type] = (typeCounts[f.type] || 0) + 1;
      });

      let content = `# ${title}\n\n`;
      content += `生成时间: ${formatDateTime(now)}\n\n`;

      content += `## 概览\n\n`;
      content += `- 客户总数: ${customers.length}\n`;
      content += `- 本期新增客户: ${periodCustomers.length}\n`;
      content += `- 本期跟进次数: ${periodFollowUps.length}\n`;
      content += `- 本期问题更新: ${periodProblems.length}\n\n`;

      content += `## 客户状态分布\n\n`;
      Object.entries(statusCounts).forEach(([status, count]) => {
        content += `- ${customerStatusLabels[status] || status}: ${count}\n`;
      });
      content += '\n';

      content += `## 跟进类型分布\n\n`;
      Object.entries(typeCounts).forEach(([type, count]) => {
        content += `- ${followUpTypeLabels[type] || type}: ${count}\n`;
      });
      content += '\n';

      content += `## 问题状态\n\n`;
      const unsolvedProblems = problems.filter((p) => p.status !== 'solved');
      const solvedProblems = problems.filter((p) => p.status === 'solved');
      content += `- 未解决: ${unsolvedProblems.length}\n`;
      content += `- 已解决: ${solvedProblems.length}\n\n`;

      if (reportType === 'customer' && selectedCustomerId) {
        const customerFollowUps = followUps.filter((f) => f.customerId === selectedCustomerId);
        const customerContacts = contacts.filter((c) => c.customerId === selectedCustomerId);
        const customer = customers.find((c) => c.id === selectedCustomerId);

        if (customer) {
          content += `## 客户详情\n\n`;
          content += `- 公司: ${customer.companyName}\n`;
          content += `- 状态: ${customerStatusLabels[customer.status]}\n`;
          content += `- 赢单概率: ${customer.winProbability}%\n`;
          content += `- 联系人数: ${customerContacts.length}\n`;
          content += `- 跟进次数: ${customerFollowUps.length}\n\n`;
        }
      }

      content += `## 下一步建议\n\n`;
      const pendingFollowUps = followUps.filter((f) => f.nextFollowUpTime && f.nextFollowUpTime > now);
      if (pendingFollowUps.length > 0) {
        content += `待跟进客户:\n`;
        pendingFollowUps.slice(0, 5).forEach((f) => {
          const customer = customers.find((c) => c.id === f.customerId);
          content += `- ${customer?.companyName || '未知'}: ${formatDate(f.nextFollowUpTime!)}\n`;
        });
      }

      await addReport({
        type: reportType,
        title,
        content,
        startDate,
        endDate: now,
        customerId: reportType === 'customer' ? selectedCustomerId : '',
        autoGenerated: false,
      });

      showNotification('报告已生成', 'success');
    } catch {
      showNotification('报告生成失败', 'error');
    }
    setGenerating(false);
  };

  const exportReport = (report: Report, format: string) => {
    if (format === 'markdown') {
      downloadFile(report.content, `${report.title}.md`, 'text/markdown');
    } else if (format === 'json') {
      downloadFile(JSON.stringify(report, null, 2), `${report.title}.json`, 'application/json');
    } else if (format === 'csv') {
      const lines = report.content.split('\n').filter((l) => l.trim());
      const csv = lines.map((l) => l.replace(/^[#-]+\s*/, '').replace(/:/g, ',')).join('\n');
      downloadFile(csv, `${report.title}.csv`, 'text/csv');
    }
    showNotification('报告已导出', 'success');
  };

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">报告生成</h1>
          <p className="text-sm text-gray-500 dark:text-gray-400">自动分析，一键生成</p>
        </div>
      </div>

      {/* Generate form */}
      <div className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-200 dark:border-gray-700">
        <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-4">生成新报告</h3>
        <div className="space-y-4">
          <div className="flex gap-3">
            <button
              onClick={() => setReportType('weekly')}
              className={`px-4 py-2 rounded-lg text-sm font-medium ${
                reportType === 'weekly' ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'
              }`}
            >
              周报
            </button>
            <button
              onClick={() => setReportType('monthly')}
              className={`px-4 py-2 rounded-lg text-sm font-medium ${
                reportType === 'monthly' ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'
              }`}
            >
              月报
            </button>
            <button
              onClick={() => setReportType('customer')}
              className={`px-4 py-2 rounded-lg text-sm font-medium ${
                reportType === 'customer' ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400' : 'bg-gray-100 dark:bg-gray-700 text-gray-600 dark:text-gray-300'
              }`}
            >
              客户报告
            </button>
          </div>

          {reportType === 'customer' && (
            <select value={selectedCustomerId} onChange={(e) => setSelectedCustomerId(e.target.value)}
              className="w-full px-3 py-2 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg text-sm text-gray-900 dark:text-white">
              <option value="">选择客户</option>
              {customers.map((c) => <option key={c.id} value={c.id}>{c.companyName}</option>)}
            </select>
          )}

          <button
            onClick={generateReport}
            disabled={generating || (reportType === 'customer' && !selectedCustomerId)}
            className="px-6 py-2 bg-emerald-600 hover:bg-emerald-700 disabled:bg-gray-400 text-white rounded-lg text-sm font-medium transition-colors"
          >
            {generating ? '生成中...' : '一键生成'}
          </button>
        </div>
      </div>

      {/* Report list */}
      <div className="space-y-3">
        <h3 className="text-sm font-semibold text-gray-900 dark:text-white">历史报告</h3>
        {reports.length === 0 ? (
          <div className="text-center py-12">
            <FileText size={48} className="mx-auto text-gray-300 dark:text-gray-600 mb-3" />
            <p className="text-gray-500 dark:text-gray-400">暂无报告</p>
          </div>
        ) : (
          reports.map((r) => (
            <div key={r.id} className="bg-white dark:bg-gray-800 rounded-xl p-4 border border-gray-200 dark:border-gray-700">
              <div className="flex items-center justify-between mb-2">
                <div className="flex items-center gap-2">
                  <FileText size={16} className="text-emerald-600" />
                  <h4 className="text-sm font-medium text-gray-900 dark:text-white">{r.title}</h4>
                  <span className="text-xs px-2 py-0.5 bg-gray-100 dark:bg-gray-700 text-gray-500 rounded">
                    {r.type === 'weekly' ? '周报' : r.type === 'monthly' ? '月报' : '客户报告'}
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-gray-400">{formatDate(r.createdAt)}</span>
                  <button onClick={() => exportReport(r, 'markdown')} className="p-1.5 rounded hover:bg-gray-100 dark:hover:bg-gray-700 text-gray-400" title="导出 Markdown">
                    <Download size={14} />
                  </button>
                  <button onClick={async () => { await deleteReport(r.id); showNotification('已删除', 'success'); }}
                    className="p-1.5 rounded hover:bg-red-50 dark:hover:bg-red-900/20 text-gray-400 hover:text-red-500">
                    <Trash2 size={14} />
                  </button>
                </div>
              </div>
              <pre className="text-xs text-gray-600 dark:text-gray-300 whitespace-pre-wrap bg-gray-50 dark:bg-gray-700/50 rounded-lg p-3 max-h-48 overflow-y-auto">
                {r.content}
              </pre>
            </div>
          ))
        )}
      </div>
    </div>
  );
}
